Repository bitnami/kube-prod-runtime, pull requests merged in 2018-10, with the labels that each got.

#177 GKE: Restrict Oauth authentication by domain suffix
  kubeprod/pkg/aks/cmd.go
  kubeprod/pkg/aks/platform.go
  kubeprod/pkg/aks/types.go
  kubeprod/pkg/gke/cmd.go
  kubeprod/pkg/gke/platform.go
  kubeprod/pkg/gke/types.go
  manifests/platforms/aks.jsonnet
  manifests/platforms/gke.jsonnet
  manifests/tests/aks.jsonnet
  manifests/tests/gke.jsonnet
Labels: gke

#168 Publish BKPR version in kubeprod/release configmap
  kubeprod/Makefile
  kubeprod/cmd/version.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/componentstatus.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/configmap.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/core_client.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/doc.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/endpoints.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/event.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/generated_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/limitrange.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/namespace.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/namespace_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/node.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/node_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/persistentvolume.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/persistentvolumeclaim.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/podtemplate.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/replicationcontroller.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/resourcequota.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/secret.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/service.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/service_expansion.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/serviceaccount.go
  kubeprod/vendor/k8s.io/client-go/kubernetes/typed/core/v1/serviceaccount_expansion.go
  kubeprod/vendor/k8s.io/client-go/tools/reference/ref.go
  kubeprod/vendor/vendor.json
  manifests/VERSION
  manifests/components/version.jsonnet
  manifests/platforms/aks.jsonnet
  manifests/platforms/gke.jsonnet
  tests/version_test.go
Labels: enhancement

#181 Reorganize README.md
  README.md
Labels: docs

#182 Remove unused etcd, gcp-broker and svc-cat manifests.
  manifests/components/etcd.jsonnet
  manifests/components/gcp-broker.jsonnet
  manifests/components/svc-cat.jsonnet
Labels: ci
