Repository bitnami/kube-prod-runtime, pull requests merged in 2018-11, with the labels that each got.

#218 update regex to fix PR discovery from git logs
  Makefile
Labels: bug

#219 Update Prometheus to 2.4.3
  manifests/components/prometheus.jsonnet
Labels: enhancement

#220 Do not collect fluentd's own logs to avoid infinite loops.
  manifests/components/fluentd-es-config/fluentd.conf
  manifests/components/fluentd-es-config/forward.input.conf
  manifests/components/fluentd-es.jsonnet
Labels: backports/queue, bug

#214 GKE: Enable integration tests
  Jenkinsfile
Labels: backports/queue, ci, gke

#225 archiver tool has been renamed to `arc`
  kubeprod/Makefile
Labels: backports/queue

#226 removes heapster from `kubeprod` namespace
  manifests/components/heapster.jsonnet
  manifests/platforms/aks.jsonnet
Labels: backports/queue

#228 docs: adds install/build guide
  README.md
  docs/install.md
  docs/quickstart-aks.md
  docs/quickstart-gke.md
  jenkins/Release_Notes.md.tmpl
Labels: backports/queue, docs

#233 Describe the advanced workflow for BKPR.
  docs/workflow.md
Labels: docs

#234 Improve kubeprod error messaging on kubectl config errors
  kubeprod/cmd/install.go
  kubeprod/cmd/version.go
Labels: backports/queue

#244 Upload release manifests to S3 bucket
  Jenkinsfile
  Makefile
  kubeprod/Makefile
  kubeprod/cmd/install.go
  kubeprod/cmd/root.go
  kubeprod/cmd/version.go
  kubeprod/main.go
Labels: backports/queue
