Repository bitnami/kube-prod-runtime, pull requests merged in 2018-12, with the labels that each got.

#250 docs: removes use of `--manifests` flag from quickstarts
  docs/install.md
  docs/quickstart-aks.md
  docs/quickstart-gke.md
Labels: backports/queue

#254 docs: adds instuction manual for app authors targetting BKPR
  docs/application-developers-reference-guide.md
Labels: backports/queue

#235 Initial implementation of Grafana
  docs/quickstart-gke.md
  kubeprod/pkg/aks/platform.go
  kubeprod/pkg/gke/platform.go
  manifests/components/grafana.jsonnet
  manifests/components/prometheus.jsonnet
  manifests/lib/utils.libsonnet
  manifests/platforms/aks.jsonnet
  manifests/platforms/gke.jsonnet
Labels: enhancement

#256 Upgrade to NGINX ingress controller 0.21.
  manifests/components/nginx-ingress.jsonnet
Labels: backports/queue, bug

#258 Better explanation on failure to set IAM policy for GKE.
  kubeprod/pkg/gke/platform.go
Labels: backports/queue

#263 Adds a troubleshooting guide
  docs/images/azure-sp-conflict.png
  docs/troubleshooting.md
Labels: backports/queue, docs

#266 docs: add quickstart section back to the readme
  README.md
Labels: backports/queue, bug, docs

#271 ci: remove tests on gke 1.9
  Jenkinsfile
Labels: backports/queue, ci

#270 docs: troubleshooting dns issues
  docs/kubeapps-on-bkpr.md
  docs/quickstart-aks.md
  docs/quickstart-gke.md
  docs/troubleshooting.md
Labels: backports/queue, docs

#284 Add diagrams for logging, monitoring and ingress stacks.
  README.md
  docs/images/ingress-stack.png
  docs/images/ingress-stack.xml
  docs/images/logging-stack.png
  docs/images/logging-stack.xml
  docs/images/monitoring-stack.png
  docs/images/monitoring-stack.xml
Labels: docs
