Repository bitnami/kube-prod-runtime, pull requests merged in 2019-03, with the labels that each got.

#410 ci: refactored Jenkinsfile to run job on a single agent node
  Jenkinsfile
  tests/ingress_test.go
Labels: ci

#419 bors: define block labels
  bors.toml
Labels: backports/queue, ci

#414 Increase nginx-ingress + oauth2_proxy to replicas=2
  manifests/components/nginx-ingress.jsonnet
  manifests/components/oauth2-proxy.jsonnet
  manifests/lib/utils.libsonnet
Labels: enhancement

#420 Quickstart for EKS.
  README.md
  docs/eks/1-Attributes.png
  docs/eks/2-Policies.png
  docs/eks/3-MFA.png
  docs/eks/4-Review.png
  docs/eks/5-User-Pool.png
  docs/eks/6-User.png
  docs/quickstart-aks.md
  docs/quickstart-eks.md
Labels: docs

#423 ci: fix github publishing in release stage
  Jenkinsfile
Labels: backports/queue

#421 docs: update references to Amazon EKS quickstart
  README.md
  docs/FAQ.md
  docs/install.md
  jenkins/Release_Notes.md.tmpl
Labels: backports/queue

#413 Update deployment when ext-dns or oauth2_proxy secret changes
  manifests/components/oauth2-proxy.jsonnet
  manifests/lib/utils.libsonnet
  manifests/platforms/aks.jsonnet
  manifests/platforms/eks.jsonnet
  manifests/platforms/gke.jsonnet
  tests/ingress_test.go
Labels: backports/queue, bug

#428 Update and fix problems in the Quickstart EKS documentation.
  docs/eks/1-Attributes.png
  docs/eks/1-new-user-pool.png
  docs/eks/2-Policies.png
  docs/eks/2-policies.png
  docs/eks/3-MFA.png
  docs/eks/3-review.png
  docs/eks/4-Review.png
  docs/eks/4-domain.png
  docs/eks/4-new-user.png
  docs/eks/5-User-Pool.png
  docs/quickstart-eks.md
Labels: docs

#433 Update github syntax highlighting hints
  docs/aks/objects.md
  docs/components.md
  docs/migration-guides/prometheus-migration.md
  docs/overrides.md
  docs/troubleshooting.md
  docs/workflow.md
Labels: docs

#430 Workaround for crashing Elasticsearch 6.x under EKS.
  docs/quickstart-eks.md
  docs/troubleshooting.md
Labels: bug

#447 ci: specify `DOCKER_CONFIG` env variable for kaniko
  Jenkinsfile
Labels: backports/queue

#456 ci: adds ownership tags to cluster resources
  Jenkinsfile
Labels: backports/queue

#457 ci: retry failed stages only once after a failure
  Jenkinsfile
Labels: backports/queue

#462 ci: adds 20 min timeout for debugging broken tests
  Jenkinsfile
Labels: backports/queue
