Repository bitnami/kube-prod-runtime, pull requests merged in 2019-04, with the labels that each got.

#490 CI: fix kubeprod install errors in the CI pipeline
  Jenkinsfile
Labels: backports/queue

#491 CI: update properties of an SOA record to speed up propagation on AKS
  Jenkinsfile
Labels: backports/queue

#487 Fix trimUrl to not trim the beginning of the URL.
  manifests/lib/utils.libsonnet
Labels: backports/queue, bug

#502 tests: retry Exporters tests on failures
  tests/monitoring_test.go
Labels: backports/queue

#513 tests: [fix] retry monitoring/exporters test
  tests/monitoring_test.go
Labels: backports/queue, bug

#511 ci: fix aks k8s version selection
  Jenkinsfile
Labels: backports/queue, bug, ci

#512 ci: ignore cluster deletion errors for EKS
  Jenkinsfile
Labels: backports/queue, ci

#515 tests: optimize retry timeouts
  tests/ingress_test.go
  tests/logging_test.go
  tests/monitoring_test.go
Labels: backports/done, ci
