Repository bitnami/kube-prod-runtime, pull requests merged in 2019-02, with the labels that each got.

#369 ci: prioritize testing on GKE over AKS
  Jenkinsfile
Labels: backports/queue

#377 Build and published kubeprod release image at kubeprod/kubeprod
  Dockerfile
  Jenkinsfile
Labels: backports/queue, ci

#342 Add EKS to jsonnet unittest
  manifests/tests/eks.jsonnet
Labels: eks

#382 ci: fixes publishing docker images during the release
  Jenkinsfile
Labels: backports/queue, bug, ci, priority/high

#388 Move the "kubernetes.io/ingress.class" annotation into TlsIngress.
  manifests/lib/utils.libsonnet
Labels: backports/queue, bug

#395 Fix GKE tests
  Jenkinsfile
Labels: bug

#405 GKE no longer supports 1.10
  Jenkinsfile
Labels: backports/queue, gke
