Repository bitnami/kube-prod-runtime, pull requests merged in 2019-01, with the labels that each got.

#296 Add documentation for Grafana.
  README.md
  docs/components.md
  manifests/components/grafana.jsonnet
Labels: docs

#297 update copyright years
  kubeprod/cmd/install.go
  kubeprod/cmd/root.go
  kubeprod/cmd/version.go
  kubeprod/main.go
  kubeprod/pkg/aks/aks.go
  kubeprod/pkg/aks/cmd.go
  kubeprod/pkg/aks/logger.go
  kubeprod/pkg/aks/platform.go
  kubeprod/pkg/aks/types.go
  kubeprod/pkg/gke/cmd.go
  kubeprod/pkg/gke/platform.go
  kubeprod/pkg/gke/platform_test.go
  kubeprod/pkg/gke/types.go
  kubeprod/pkg/installer/install.go
  kubeprod/pkg/prodruntime/manifest.go
  kubeprod/pkg/prodruntime/platforms.go
  kubeprod/tools/godeps.sh
  kubeprod/tools/rand.go
  kubeprod/tools/url.go
  manifests/components/alertmanager-config.jsonnet
  manifests/components/cert-manager.jsonnet
  manifests/components/elasticsearch.jsonnet
  manifests/components/externaldns.jsonnet
  manifests/components/fluentd-es-config/import-from-upstream.py
  manifests/components/fluentd-es.jsonnet
  manifests/components/grafana.jsonnet
  manifests/components/kibana.jsonnet
  manifests/components/nginx-ingress.jsonnet
  manifests/components/oauth2-proxy.jsonnet
  manifests/components/prometheus-config.jsonnet
  manifests/components/prometheus.jsonnet
  manifests/components/version.jsonnet
  manifests/lib/kube.libsonnet
  manifests/lib/utils.libsonnet
  manifests/platforms/aks.jsonnet
  manifests/platforms/gke.jsonnet
  manifests/tests/aks.jsonnet
  manifests/tests/gke.jsonnet
  tests/ingress_test.go
  tests/integration_suite_test.go
  tests/logging_test.go
  tests/monitoring_test.go
  tests/testdata/ingress-deploy.yaml
  tests/testdata/ingress-ingress.yaml
  tests/testdata/ingress-service.yaml
  tests/testdata/logging-deploy.yaml
  tests/testdata/monitoring-deploy.yaml
  tests/testdata/prometheus-crashloop-alerts.jsonnet
  tests/version_test.go
Labels: backports/queue, housekeeping

#298 docs: rename quickstart env var `GCLOUD_REGION` to `GCLOUD_ZONE`
  docs/quickstart-gke.md
Labels: bug, docs, gke

#301 Upgrade addon-resizer to 1.8.4
  manifests/components/prometheus.jsonnet
Labels: bug

#302 Add basic roadmap document
  README.md
  docs/FAQ.md
  docs/roadmap.md
Labels: docs

#303 Drop AKS 1.9.x from testing matrix
  Jenkinsfile
Labels: backports/queue

#311 More robust check for elasticsearch timeseries
  tests/monitoring_test.go
Labels: bug

#312 docs: adds upgrading section to quickstart and workflow guides
  docs/migration-guides/prometheus-migration.md
  docs/quickstart-aks.md
  docs/quickstart-gke.md
  docs/workflow.md
Labels: backports/queue, docs

#332 Initial support for EKS manifests
  manifests/platforms/eks.jsonnet
Labels: aws, enhancement

#341 CI: Update AKS version test cluster setup
  Jenkinsfile
Labels: backports/queue, ci

#333 automation: infrastructure to automate BKPR component updates
  jenkins/automation/Jenkinsfile
  jenkins/automation/automatic-updates.sh
  jenkins/automation/functions
Labels: ci

#345 ci: automatically use latest k8s PATCH versions for AKS test clusters
  Jenkinsfile
Labels: backports/queue, ci
